APIGW Service

@hostname = http://127.0.0.1:8080

### Case 1: APIGW Service with no auth

GET {{hostname}}


### Case 2: test metrics

GET {{hostname}}/metrics


### Case 3: get user keys.

GET {{hostname}}/v1/user/key/list

### Case 4: create user keys
POST {{hostname}}/v1/user/key/create



### Case 4: sensitive

GET {{hostname}}/v1/sensitive

###
GET {{hostname}}/v1/sensitive/list


### Case 4: create user keys
POST {{hostname}}/v1/sensitive/create

{
    "category": "test",
    "country_code": "CHN",
    "content": "test content"
}

### IPDB DataCenter API
POST {{hostname}}/v1/ipdb/datacenter/create

{
    "name": "Tencent Cloud",
    "isp_domain": "https://intl.cloud.tencent.com/",
    "ip_start": "1.12.0.0",
    "ip_end": "1.15.255.255",
    "created_ts": "17563648",
    "updated_ts": "17825791"
}