version: '3'

vars:
  SERVICE: noah
  DATE:
    sh: date "+%Y.%m%d.%H%M"
  
tasks:
  default:
    desc: Show help messages
    silent: true
    cmds:
      - echo "Welcome to use go-task!"
      - echo
      - |
        task --list --sort=none

includes:
    buf: 
      dir: ./apis/
      taskfile: ./apis/Taskfile.yml

    build:
      dir: ./build/
      taskfile: ./build/Taskfile.yml